TECH-316: Add "Overall Compatibility" column to the Products table
GovStackWorkingGroup/testing-webapp pull request #22
Opened 2023-03-01 12:42 UTC by KarolinaKopacz

**Description**:
Add "Overall Compatibility" column to the Products table.

**Implemented solution detail:**
<img width="1519" alt="Zrzut ekranu 2023-03-1 o 13 42 25" src="https://user-images.githubusercontent.com/80507519/222142556-4dae90df-84d2-41e0-9727-0100b17825f9.png">

2023-03-01 12:44 UTC, KarolinaKopacz commented
@dborowiecki @mgrochalskisoldevelo please do not merge before https://github.com/GovStackWorkingGroup/testing-webapp/pull/16

2023-03-02 15:41 UTC, dborowiecki requested changes
Please change the display function to not display fractional part.

2023-03-02 15:41 UTC, dborowiecki commented on components/table/ProductTableRow.tsx
> +          <p>{`${product.overallCompatibility === 1 ? '100' : (product.overallCompatibility*100).toFixed(2)}%`}</p>
I think we can just keep integer for all values not only 100. I know that we have more data coming from the backend, but we should be consistent with mocks.

2023-03-02 16:20 UTC, dborowiecki approved these changes

2023-03-02 16:20 UTC, merged