TECH-514: Add autocomplete for Software search (FE)
GovStackWorkingGroup/testing-webapp pull request #39
Opened 2023-04-05 12:00 UTC by KarolinaKopacz

**Description:**
Add autocomplete for Software search (FE)
Ticket: https://govstack-global.atlassian.net/browse/TECH-514

**Implemented solution detail:**
<img width="330" alt="Zrzut ekranu 2023-04-5 o 13 42 38" src="https://user-images.githubusercontent.com/80507519/230074030-d54b22f2-fd48-4bb4-9d7d-9c854930e52c.png">
<img width="321" alt="Zrzut ekranu 2023-04-5 o 13 42 21" src="https://user-images.githubusercontent.com/80507519/230074047-a70947d9-efdc-4258-b33a-d859b32c279e.png">

2023-04-05 13:04 UTC, KarolinaKopacz commented
@dszafranek please do not merge before https://govstack-global.atlassian.net/browse/TECH-513

2023-04-05 13:55 UTC, dszafranek requested changes

2023-04-05 13:55 UTC, dszafranek commented on components/shared/SearchInput.tsx
> +  placeholder = 'Search',
This should be translated

2023-04-05 13:55 UTC, dszafranek commented on components/shared/SearchInput.tsx
> +    color: 'rgba(193, 193, 193, 1)',
Is it possible to move these styles out of txs and to .less file?
Or maybe use classes and style them in .less:
https://react-select.com/styles#the-classnames-prop

2023-04-12 07:59 UTC, dszafranek approved these changes

2023-04-12 08:13 UTC, merged