TECH-418: Add sorting to the Product table
GovStackWorkingGroup/testing-webapp pull request #40
Opened 2023-04-05 15:20 UTC by KarolinaKopacz

**Description:**
Add sorting to the Product table.
Ticket: https://govstack-global.atlassian.net/browse/TECH-418

**Implemented solution detail:**

https://user-images.githubusercontent.com/80507519/231485431-f6ef31a6-4f03-4c1e-bed3-54a518343f48.mov

2023-04-06 12:05 UTC, dszafranek requested changes
Icons should change when you click on a header so it's visible to the user which field he's currently sorting.

In the current implementation, only one field can be sorted at a time. If BE can support it there should also be support for sorting by multiple fields (ex: sortBy name asc, compatibility desc).

2023-04-12 14:16 UTC, KarolinaKopacz commented
@dszafranek The design is updated (different icons than in figma mocks)

2023-04-17 07:20 UTC, dszafranek approved these changes

2023-05-02 15:04 UTC, dszafranek approved these changes

2023-05-02 15:04 UTC, merged