Moved all frontend files to the src folder
GovStackWorkingGroup/testing-webapp pull request #70
Opened 2023-10-10 11:28 UTC by KarolinaKopacz

Moved all frontend files to the src folder

2023-10-10 12:04 UTC, dborowiecki requested changes
looks good, i left one comment

2023-10-10 12:04 UTC, dborowiecki commented on src/package.json
> -    "dev": "next dev -p 3003",
I think we should keep 3003 to be consistent

2023-10-10 12:48 UTC, lruzicki commented
Some changes in .circleci/config.yml may be required after moving package.json.
[here](https://github.com/GovStackWorkingGroup/testing-webapp/blob/develop/.circleci/config.yml#L16) you can change it to run yarn in the directory where the package.json is available.

2023-10-11 09:24 UTC, lruzicki approved these changes
Looks good

next time you can squash repeated commits simply with `git rebase -i HEAD~31`

2023-10-11 10:50 UTC, dborowiecki approved these changes

2023-10-11 10:51 UTC, merged